<a href="https://colab.research.google.com/github/AzucenaIglesias/NumPyExercises/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###First steps with numpy###

import numpy as np

#Create a NumPy array- One Dimensional Array

one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

#two-dimensional array- Specify an extra layer of square brackets

two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

# Arrays with sequences of numbers
sequence_of_integers = np.arange(6, 15)
print(sequence_of_integers)

# Arrays with random numbers

random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6,))
print(random_integers_between_50_and_100)

# Random floating-point values
random_floats_between_0_and_1 = np.random.random((6,))
print(random_floats_between_0_and_1)

## Mathematical Operations on NumPy
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

#Create a Linear Dataset

feature= np.arange(6,21)
print(feature)
label=(feature*3) + 4
print(label)

#Add Noise to a Dataset

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise
print(label)



[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]
[[ 6  5]
 [11  7]
 [ 4  8]]
[ 6  7  8  9 10 11 12 13 14]
[68 51 98 59 78 82]
[0.09346584 0.57283272 0.02595751 0.87609305 0.92940172 0.9928496 ]
[2.09346584 2.57283272 2.02595751 2.87609305 2.92940172 2.9928496 ]
[204 153 294 177 234 246]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
[ 0.05560156 -1.92970289 -1.39476367  1.68523774  0.86634844  0.26601106
  1.43862946 -1.39477833  0.07454852  1.50226478 -0.30623597  0.20555835
 -0.70296757 -0.32727907 -1.73676448]
[22.05560156 23.07029711 26.60523633 32.68523774 34.86634844 37.26601106
 41.43862946 41.60522167 46.07454852 50.50226478 51.69376403 55.20555835
 57.29703243 60.67272093 62.26323552]
